export const DummyData = {
  grid: [
    [
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 2,
      },
      {
        isOpen: false,
        isMine: true,
        isFlagged: true,
        isExploded: false,
        value: 0,
      },
      {
        isOpen: false,
        isMine: true,
        isFlagged: true,
        isExploded: false,
        value: 0,
      },
      {
        isOpen: false,
        isMine: true,
        isFlagged: true,
        isExploded: false,
        value: 0,
      },
      {
        isOpen: false,
        isMine: true,
        isFlagged: true,
        isExploded: false,
        value: 0,
      },
      {
        isOpen: false,
        isMine: true,
        isFlagged: true,
        isExploded: false,
        value: 0,
      },
      {
        isOpen: false,
        isMine: true,
        isFlagged: true,
        isExploded: false,
        value: 0,
      },
      {
        isOpen: false,
        isMine: true,
        isFlagged: true,
        isExploded: false,
        value: 0,
      },
      {
        isOpen: false,
        isMine: true,
        isFlagged: true,
        isExploded: false,
        value: 0,
      },
      {
        isOpen: false,
        isMine: true,
        isFlagged: true,
        isExploded: false,
        value: 0,
      },
    ],
    [
      {
        isOpen: false,
        isMine: true,
        isFlagged: false,
        isExploded: true,
        value: 0,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
    ],
    [
      {
        isOpen: true,
        isMine: true,
        isFlagged: false,
        isExploded: true,
        value: 0,
      },
      {
        isOpen: true,
        isMine: false,
        isFlagged: true,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: true,
        isMine: true,
        isFlagged: true,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: true,
        isMine: true,
        isFlagged: true,
        isExploded: true,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
    ],
    [
      {
        isOpen: false,
        isMine: true,
        isFlagged: false,
        isExploded: true,
        value: 0,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
    ],
    [
      {
        isOpen: false,
        isMine: true,
        isFlagged: false,
        isExploded: true,
        value: 0,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
    ],
    [
      {
        isOpen: false,
        isMine: true,
        isFlagged: false,
        isExploded: true,
        value: 0,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
    ],
    [
      {
        isOpen: false,
        isMine: true,
        isFlagged: false,
        isExploded: true,
        value: 0,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
    ],
    [
      {
        isOpen: false,
        isMine: true,
        isFlagged: false,
        isExploded: true,
        value: 0,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
    ],
    [
      {
        isOpen: false,
        isMine: true,
        isFlagged: false,
        isExploded: true,
        value: 0,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
    ],
    [
      {
        isOpen: false,
        isMine: true,
        isFlagged: false,
        isExploded: true,
        value: 0,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: true,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 0,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: true,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 4,
      },
    ],
  ],
};

export const DummyHighScores = {
  highScores: [
    {
      id: 0,
      score: "01:32",
      date: "2021/07/01",
    },
    {
      id: 1,
      score: "01:32",
      date: "2021/07/01",
    },
    {
      id: 2,
      score: "01:32",
      date: "2021/07/01",
    },
    {
      id: 3,
      score: "01:32",
      date: "2021/07/01",
    },
    {
      id: 4,
      score: "01:32",
      date: "2021/07/01",
    },
    {
      id: 5,
      score: "01:32",
      date: "2021/07/01",
    },
    {
      id: 6,
      score: "01:32",
      date: "2021/07/01",
    },
    {
      id: 7,
      score: "01:32",
      date: "2021/07/01",
    },
    {
      id: 8,
      score: "01:32",
      date: "2021/07/01",
    },
    {
      id: 9,
      score: "01:32",
      date: "2021/07/01",
    },
  ],
};
