export const DummyData = {
  grid: [
    [
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 2,
      },
      {
        isOpen: false,
        isMine: true,
        isFlagged: true,
        isExploded: false,
        value: 0,
      },
      {
        isOpen: false,
        isMine: true,
        isFlagged: true,
        isExploded: false,
        value: 0,
      },
      {
        isOpen: false,
        isMine: true,
        isFlagged: true,
        isExploded: false,
        value: 0,
      },
      {
        isOpen: false,
        isMine: true,
        isFlagged: true,
        isExploded: false,
        value: 0,
      },
      {
        isOpen: false,
        isMine: true,
        isFlagged: true,
        isExploded: false,
        value: 0,
      },
      {
        isOpen: false,
        isMine: true,
        isFlagged: true,
        isExploded: false,
        value: 0,
      },
      {
        isOpen: false,
        isMine: true,
        isFlagged: true,
        isExploded: false,
        value: 0,
      },
      {
        isOpen: false,
        isMine: true,
        isFlagged: true,
        isExploded: false,
        value: 0,
      },
      {
        isOpen: false,
        isMine: true,
        isFlagged: true,
        isExploded: false,
        value: 0,
      },
    ],
    [
      {
        isOpen: false,
        isMine: true,
        isFlagged: false,
        isExploded: true,
        value: 0,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
    ],
    [
      {
        isOpen: false,
        isMine: true,
        isFlagged: false,
        isExploded: true,
        value: 0,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
    ],
    [
      {
        isOpen: false,
        isMine: true,
        isFlagged: false,
        isExploded: true,
        value: 0,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
    ],
    [
      {
        isOpen: false,
        isMine: true,
        isFlagged: false,
        isExploded: true,
        value: 0,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
    ],
    [
      {
        isOpen: false,
        isMine: true,
        isFlagged: false,
        isExploded: true,
        value: 0,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
    ],
    [
      {
        isOpen: false,
        isMine: true,
        isFlagged: false,
        isExploded: true,
        value: 0,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
    ],
    [
      {
        isOpen: false,
        isMine: true,
        isFlagged: false,
        isExploded: true,
        value: 0,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
    ],
    [
      {
        isOpen: false,
        isMine: true,
        isFlagged: false,
        isExploded: true,
        value: 0,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
    ],
    [
      {
        isOpen: false,
        isMine: true,
        isFlagged: false,
        isExploded: true,
        value: 0,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: false,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 1,
      },
      {
        isOpen: true,
        isMine: false,
        isFlagged: false,
        isExploded: false,
        value: 4,
      },
    ],
  ],
};
