name: Run Terraform
on:
  push:
    branches: [ "Josh/Actions" ]
  pull_request:
    branches: [ "main" ]

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: infrastructure
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.8.2

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform
        run: terraform apply -auto-approve -debug
        env:
            TF_VAR_ACCESS_KEY: ${{ secrets.access_key }}
            TF_VAR_SECRET_KEY: ${{ secrets.secret_key }}
            TF_VAR_DB_USERNAME: ${{ secrets.db_username }}
            TF_VAR_DB_PASSWORD: ${{ secrets.db_password }}
            TF_VAR_SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

  upload:
    needs: terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}