name: Run Terraform

on:
  push:
    branches: [ "Josh/Actions" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: infrastructure
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform
        id: init
        run: terraform init

      - name: Generate infrastructure plan
        id: plan
        run: terraform plan -out=.tfplan

      - name: Apply infrastructure plan
        id: apply
        run: terraform apply .tfplan

  upload:
    needs: deploy-infrastructure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
